### ISSUE TITLE
The module doesn't work

### ISSUE THREAD

**Issue by adriano18** [eideasy/whmcs-eid-login#1]
Hello,

I installed the module, but the code does not work.

`{if !$loggedin}
    {eid_easy_login_html}<br />
{/if}`

Screenshot https://i.vgy.me/r1SpUA.png

Once the code is inserted, the billing stops working, if I set the function {literal}, it just outputs the code without anything.

How to fix a bug?

**Comment by smartman** [comment]
Do you have WHMCS 8? Currently it is tested only with 7 and we are planning to test it with WHMCS 8 next week or week after that.
What countries eID is most interesting to you? We could add more support with this change.

**Comment by smartman** [comment]
WHMCS 8 support also added now. Please let me know how does it work for you now? There was also typo in the instructions. Correct code to paste into the login page template is this
{if !$loggedin} {$eid_easy_login_html}<br /> {/if}

**Comment by adriano18** [comment]
Hello,

I installed a new version and receied this error https://i.vgy.me/mz8hQK.png
How to fix this?

_If you increase the list of European countries, it will be great (Scandinavian countries, central Europe) especially interesting._

**Comment by adriano18** [comment]
Module config https://i.vgy.me/9GxhEd.png

**Comment by adriano18** [comment]
Now it works, how to make it appear in the client's account panel and can be connected to the client's account? 
![image](https://user-images.githubusercontent.com/11743482/98449636-bd71b700-213d-11eb-8ba5-d8375bf2dce4.png)

https://billing.yotta.host/login Nothing happens now if I want to log in to my account.

**Comment by smartman** [comment]
Errors during login are written into System Activity Logs. Is there any errors in the System Activity Logs? What is the exact WHMCS version?

SQL error indicates that tblusers id field is not what it is expected to be. can you send output of mysql "show create table tblusers" and "show create table mod_eideasy_users"
In my machine it looks like that

```
CREATE TABLE `tblusers` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `first_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `last_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `password` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `language` varchar(32) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `second_factor` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `second_factor_config` text COLLATE utf8_unicode_ci,
  `remember_token` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `reset_token` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `security_question_id` int unsigned NOT NULL DEFAULT '0',
  `security_question_answer` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `last_ip` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `last_hostname` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `last_login` timestamp NULL DEFAULT NULL,
  `email_verification_token` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `email_verification_token_expiry` timestamp NULL DEFAULT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `reset_token_expiry` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tblusers_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```
and
```
CREATE TABLE `mod_eideasy_users` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `idcode` text COLLATE utf8_unicode_ci NOT NULL,
  `country` text COLLATE utf8_unicode_ci NOT NULL,
  `firstname` text COLLATE utf8_unicode_ci NOT NULL,
  `lastname` text COLLATE utf8_unicode_ci NOT NULL,
  `user_id` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `mod_eideasy_users_user_id_foreign` (`user_id`),
  CONSTRAINT `mod_eideasy_users_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `tblusers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

**Comment by adriano18** [comment]
Error corrected, I re-saved the module.

**Comment by smartman** [comment]
Great news!
